config/routes.rb
Rails.application.routes.draw do

  get 'shop' => 'store_front#index'

  get 'about' => 'store_front#about'

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create]
  resources :orders, only: [:new, :create, :show]
  devise_for :users
  scope :admin do
  resources :products
  resources :brands
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  
  root 'store_front#index'
  
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Las Vegas Online Jewelry</a>
    </div>

    <%= render 'layouts/navbar_links' %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Backroom <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Brands', brands_path %></li>
          <li><%= link_to 'Categories', categories_path %></li>
          <li><%= link_to 'Products', products_path %></li>
        </ul>
      </li>
    <% end %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, shop_path(category_id: category.id) %></li>
        <% end %>
        <li class="divider"></li>
        <li><%= link_to 'All Products', shop_path %></li>
      </ul>
    </li>
    <li><%= link_to 'About', about_path %></li>
  </ul>

  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to fa_icon('shopping-cart', text: 'Your Cart'), edit_cart_path %></li>
  <li>
  <%= form_tag(shop_path, method: :get, role: 'search', class: 'navbar-form') do %>
    <div class="form-group">
      <%= text_field_tag(:search, nil, placeholder: 'Search Products', class: 'form-control input-sm') %>
    </div>
    <%= submit_tag('Search', class: 'btn btn-default btn-sm') %>
  <% end %>
</li>

    <% if user_signed_in? %>
      <li><%= link_to 'Account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <li><%= link_to 'Register', new_user_registration_path %></li>
    <% end %>
  </ul>
</div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TerryStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render'layouts/navbar' %>
    <div id="notice"><%= notice %></div>
    <%= yield %>
  </body>
</html>